version: '3.8'

services:
  app:
    image: phuoc20207/ha:latest
    ports:
      - "7999:7999"
    volumes:
      - ./setup.sh:/app/setup.sh  # Mount the setup script into the container
    environment:
      - HOME=/app
    entrypoint: >
      sh -c "/app/setup.sh &&
      cd /app/study_center/face_recognition &&
      python src/face_phuoc.py"
