version: '3.8'

services:
  app:
    image:
      phuoc20207/cloud_basic
    command: sh -c "cd /app/study_center/face_recognition && python src/face_phuoc.py"
    ports:
      - "3000:80"
    expose:
      - 3000
